minio:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  secure: false

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue: training_updates